//! Data type definitions for the contagion mechanic.
//!
//! This module defines the core data structures used by the contagion system:
//! - `ContagionConfig`: Static configuration shared across all entities
//! - `InfectionState`: Per-entity mutable state
//! - `ContagionInput`: Per-frame input data
//! - `ContagionEvent`: Events emitted by the mechanic

/// Static configuration for a contagion mechanic.
///
/// This configuration is typically stored as a resource in the game engine
/// and shared across all entities that use the contagion mechanic.
///
/// # Examples
///
/// ```
/// use issun_core::mechanics::contagion::ContagionConfig;
///
/// let config = ContagionConfig {
///     base_rate: 0.05, // 5% base infection chance per frame
/// };
/// ```
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ContagionConfig {
    /// Base infection rate (0.0 to 1.0).
    ///
    /// This represents the baseline probability of infection spread
    /// before any modifiers (density, resistance, etc.) are applied.
    pub base_rate: f32,
}

impl Default for ContagionConfig {
    fn default() -> Self {
        Self { base_rate: 0.1 }
    }
}

/// Simple severity-based infection state.
///
/// This is a simplified state representation using a single numeric severity value.
/// For more advanced state machines with incubation/active/recovered stages,
/// see `state::InfectionState`.
///
/// # Examples
///
/// ```
/// use issun_core::mechanics::contagion::SimpleSeverity;
///
/// // Healthy entity
/// let healthy = SimpleSeverity::default();
/// assert_eq!(healthy.severity, 0);
///
/// // Infected entity
/// let infected = SimpleSeverity { severity: 5 };
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct SimpleSeverity {
    /// Current severity level (0 = healthy, higher = more severe).
    ///
    /// - 0: Healthy (not infected)
    /// - 1+: Infected (higher values indicate more severe infection)
    pub severity: u32,
}

/// Per-frame input for contagion calculation.
///
/// This input is constructed fresh each frame from the game world state
/// and contains all the information needed to calculate infection spread
/// for a single entity.
///
/// # Examples
///
/// ```
/// use issun_core::mechanics::contagion::ContagionInput;
///
/// let input = ContagionInput {
///     density: 0.8,      // High population density
///     resistance: 5,     // Moderate resistance
///     rng: 0.42,         // Random value for this frame
/// };
/// ```
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ContagionInput {
    /// Population density around this entity (0.0 to 1.0).
    ///
    /// Higher density increases the chance of infection spread.
    /// - 0.0: Isolated (no nearby entities)
    /// - 1.0: Maximum density
    pub density: f32,

    /// Entity's resistance to infection (higher = more resistant).
    ///
    /// This value is typically derived from entity stats or attributes.
    /// The meaning of specific values depends on the `ProgressionPolicy`.
    pub resistance: u32,

    /// Random value for this frame (0.0 to 1.0).
    ///
    /// This value should be generated by the game engine's RNG system
    /// to ensure deterministic behavior (e.g., for replays or networking).
    pub rng: f32,
}

/// Events emitted by the contagion mechanic.
///
/// These events communicate state changes to the game world without
/// coupling the mechanic to a specific engine.
///
/// # Examples
///
/// ```
/// use issun_core::mechanics::contagion::ContagionEvent;
///
/// let event = ContagionEvent::Infected;
/// match event {
///     ContagionEvent::Infected => println!("Entity became infected!"),
///     ContagionEvent::Progressed { new_severity } => {
///         println!("Infection progressed to severity {}", new_severity);
///     }
/// }
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ContagionEvent {
    /// Entity became newly infected.
    ///
    /// This event is emitted when an entity transitions from healthy (severity 0)
    /// to infected (severity > 0).
    Infected,

    /// Infection progressed to a more severe state.
    ///
    /// This event is emitted when an already-infected entity's severity increases.
    Progressed {
        /// The new severity level after progression.
        new_severity: u32,
    },
}
