//! Data models layer
//!
//! Pure data structures without business logic

pub mod entities;
pub mod scenes;
pub mod game_context;
pub mod game_scene;
pub mod scene_handler;

pub use game_context::GameContext;
pub use game_scene::{GameScene, GameState}; // GameState is auto-generated by Scene derive macro
pub use scene_handler::handle_scene_input;
